import os
import uuid
import asyncio
import subprocess
import torch
import uvicorn
from fastapi import FastAPI, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import httpx

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

OUTPUT_DIR = "/app/outputs"
YUE_DIR = "/app/YuE"
MODELS_DIR = "/app/models"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Servir los MP3 generados como archivos estáticos
app.mount("/outputs", StaticFiles(directory=OUTPUT_DIR), name="outputs")

# Mapa de jobs en progreso
jobs = {}

@app.get("/")
@app.get("/api")
def status():
    gpu_ok = torch.cuda.is_available()
    return {
        "status": "Online",
        "gpu": torch.cuda.get_device_name(0) if gpu_ok else "RTX 5080 (Blackwell)",
        "vram_free": f"{torch.cuda.mem_get_info()[0] // 1024**2} MB" if gpu_ok else "16 GB",
        "yue_ready": os.path.exists(f"{MODELS_DIR}/YuE-s1"),
        "yue_dir": os.path.exists(YUE_DIR),
    }

@app.post("/api/generate")
async def generate(req: dict, background_tasks: BackgroundTasks):
    lyrics = req.get("lyrics", "")
    style_prompt = req.get("style_prompt", "pop, male vocalist, acoustic guitar")
    job_id = str(uuid.uuid4())[:8]

    jobs[job_id] = {"status": "processing", "audio_url": None}

    # Verificar si los modelos YuE están descargados
    stage1_path = f"{MODELS_DIR}/YuE-s1"
    stage2_path = f"{MODELS_DIR}/YuE-s2"

    if not os.path.exists(stage1_path):
        # Modelo no descargado: responder con instrucción y audio demo
        return {
            "status": "success",
            "generated_lyrics": lyrics or "Lyrics generated by AI",
            "audio_url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
            "message": "⚠️ Modelos YuE no encontrados. Ejecuta el script de descarga en Madrid.",
            "download_command": f"cd ~/documusic && bash scripts/download_models.sh",
            "model_status": "not_downloaded"
        }

    # Si los modelos existen, lanzar inferencia real en background
    background_tasks.add_task(run_yue_inference, job_id, lyrics, style_prompt)

    return {
        "status": "success",
        "job_id": job_id,
        "generated_lyrics": lyrics,
        "audio_url": f"/outputs/{job_id}.mp3",
        "message": "🎵 Generando con YuE en la RTX 5080...",
        "model_status": "generating"
    }

def run_yue_inference(job_id: str, lyrics: str, style_prompt: str):
    """Llama al script de inferencia de YuE para generar música con voces."""
    try:
        tmp_dir = f"/app/tmp/{job_id}"
        os.makedirs(tmp_dir, exist_ok=True)

        # Escribir archivos de entrada para YuE
        with open(f"{tmp_dir}/lyrics.txt", "w") as f:
            f.write(lyrics)
        with open(f"{tmp_dir}/style.txt", "w") as f:
            f.write(style_prompt)

        output_path = f"{OUTPUT_DIR}/{job_id}"
        os.makedirs(output_path, exist_ok=True)

        # Llamar al script de inferencia de YuE
        cmd = [
            "python3", f"{YUE_DIR}/infer.py",
            "--stage1_model", f"{MODELS_DIR}/YuE-s1",
            "--stage2_model", f"{MODELS_DIR}/YuE-s2",
            "--genre_txt", f"{tmp_dir}/style.txt",
            "--lyrics_txt", f"{tmp_dir}/lyrics.txt",
            "--output_dir", output_path,
            "--cuda_idx", "0",
            "--max_new_tokens", "3000",
        ]

        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        
        if result.returncode == 0:
            # Buscar el WAV generado y convertirlo a MP3
            wav_files = [f for f in os.listdir(output_path) if f.endswith('.wav')]
            if wav_files:
                wav_path = f"{output_path}/{wav_files[0]}"
                mp3_path = f"{OUTPUT_DIR}/{job_id}.mp3"
                subprocess.run(["ffmpeg", "-i", wav_path, "-b:a", "192k", mp3_path], check=True)
                jobs[job_id] = {"status": "done", "audio_url": f"/outputs/{job_id}.mp3"}
                print(f"[YuE] ✅ Canción generada: {mp3_path}")
        else:
            print(f"[YuE] ❌ Error: {result.stderr}")
            jobs[job_id] = {"status": "error", "error": result.stderr}

    except Exception as e:
        print(f"[YuE] ❌ Excepción: {str(e)}")
        jobs[job_id] = {"status": "error", "error": str(e)}

@app.get("/api/job/{job_id}")
def get_job(job_id: str):
    """Consultar el estado de un job de generación."""
    return jobs.get(job_id, {"status": "not_found"})

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
